version: 2

models:
  - name: stations_summary
    description: "A metadata information about 53 stations"
    # columns:
    #     - name: id
    #       description: "The primary key for this table"
    #       tests:
    #           - unique
    #           - not_null

  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
    # columns:
    #     - name: id
    #       description: "The primary key for this table"
    #       tests:
    #           - unique
    #           - not_null
